### ISSUE TITLE
Update to jsdoc 4.0

### ISSUE THREAD

**Issue by dasa** [bsvensson/jsdoc#3]
This will pick up the fix for https://github.com/jsdoc/jsdoc/issues/2036

**Comment by bsvensson** [comment]
@lheberlie - will you test this?

**Comment by dasa** [comment]
@lheberlie have you had a chance to test this yet?

**Comment by dasa** [comment]
Done at https://github.com/bsvensson/jsdoc/tree/esrijs-sdk
